### ISSUE TITLE
ERROR: java.lang.IllegalArgumentException: Base position exceeds Integer.MAX_VALUE

### ISSUE THREAD

**Issue by zhangnan0107** [Wedge-lab/battenberg#106]
Hi authors,

Thanks for development this tool.

I am using the dev branch on a small test data set which included around 10,000,000 reads in both normal and tumor BAMs. There was an error during phasing step. Do you might know the reason for this?

```
Phasing iteration 10:          0 seconds
Phasing iteration 11:          0 seconds
Phasing iteration 12:          0 seconds

Window 4 (X:2699246-154933511)
Reference markers:           4
Study markers:               4
ERROR: java.lang.IllegalArgumentException: Base position exceeds Integer.MAX_VALUE
Are all genetic distances in cM units (in command line and in genetic map)?
java.lang.IllegalArgumentException: Base position exceeds Integer.MAX_VALUE
Are all genetic distances in cM units (in command line and in genetic map)?
        at vcf.PlinkGenMap.basePos(PlinkGenMap.java:365)
        at vcf.WindowIt$Reader.run(WindowIt.java:262)
        at java.lang.Thread.run(Thread.java:750)
Burnin  iteration 4:           2 seconds
Phasing iteration 11:          3 seconds
Burnin  iteration 5:           2 seconds
Phasing iteration 10:          3 seconds
Phasing iteration 12:          2 seconds
Burnin  iteration 6:           16 seconds
Burnin  iteration 6:           17 seconds

Window 2 (22:33510303-51237071)
Reference markers:     142,508
Study markers:         142,508
``` 

At the end of the log, there was another error - `task 23 failed - "EXIT_CODE == 0 is not TRUE"`, which I guess came from the above one. In addition, I also got the write_tsv error as many other people did. I tried adding `write_battenberg_phasing=F` when calling the battenberg function, which however didn't work. Would you also provide some suggestions regarding this?

```
Phasing iteration 11:          2 seconds
Phasing iteration 12:          2 seconds

Cumulative Statistics:

Study markers:         439,494

Haplotype phasing time:        4 minutes 21 seconds
Total time:                    4 minutes 48 seconds

End time: 06:43 PM CEST on 31 Jul 2023
beagle.24Aug19.3e8.jar finished
Error in { : task 23 failed - "EXIT_CODE == 0 is not TRUE"
Calls: battenberg -> %dopar% -> <Anonymous>
In addition: Warning message:
The `path` argument of `write_tsv()` is deprecated as of readr 1.4.0.
ℹ Please use the `file` argument instead.
ℹ The deprecated feature was likely used in the Battenberg package.
  Please report the issue to the authors.
Execution halted
rm: missing operand
Try 'rm --help' for more information.
Exit code is not equal to zero. There is an error.

``` 

Thanks!

**Comment by jcesar101** [comment]
Hi,

and thank you for using Battenberg.

This error is thrown by Beagle and it's, in theory, caused by a base position being larger than 2,147,483,647, although we cannot trace back the actual root cause as we are only using beagle as an external phasing tool. We found a couple of inquiries about a similar problem, but no actual response was provided:

- https://www.biostars.org/p/391859/
- https://www.biostars.org/p/409356/

Our recommendation is to use the most recent release of the Beagle tool and/or write to the [authors ](browning@uw.edu) about this issue.

Regarding the write_tsv function warning, it's caused by a breaking change in a recent update of the R readr package, but it's not affecting the pipeline outcome and it is already scheduled to be fixed in the next release of Battenberg.
